# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
